#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|     Opção inválida!{'|': >6}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n| Nome não deve ser vazio{'|': >2}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|   Aluno não encontrado{'|': >3}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|    Ação interrompida{'|': >5}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^62}\n╔{'─'*60}╗\n|     Nome deve conter apenas letras e deve ser composto{'|': >6}\n╚{'─'*60}╝\n")
#print(f"\n{'⚠': ^32}\n╔{'─'*30}╗\n|   Matricula não encontrada{'|': >4}\n╚{'─'*30}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n| A matricula não pode ser vazia{'|': >2}\n╚{'─'*32}╝\n")
#print(f"\n╔{'─'*30}╗\n|  Aluno deletado com sucesso{'|': >3}\n╚{'─'*30}╝\n")
#print(f"\n╔{'─'*30}╗\n| Aluno adicionado com sucesso{'|': >2}\n╚{'─'*30}╝\n")
#print(f"\n╔{'─'*30}╗\n| Aluno atualizado com sucesso{'|': >2}\n╚{'─'*30}╝\n")
#print(f"\n{'⚠': ^30}\n╔{'─'*28}╗\n|  Professor não encontrado{'|': >3}\n╚{'─'*28}╝\n")
#print(f"\n╔{'─'*35}╗\n| Professor adicionado com sucesso{'|': >3}\n╚{'─'*35}╝\n")
#print(f"\n╔{'─'*35}╗\n| Professor atualizado com sucesso{'|': >3}\n╚{'─'*35}╝\n")
#print(f"\n╔{'─'*35}╗\n|   Professor deletado com sucesso{'|': >3}\n╚{'─'*35}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n|   A turma não pode ser vazia{'|': >4}\n╚{'─'*32}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|    Turma já existente{'|': >4}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n|   Aluno já presente na turma{'|': >4}\n╚{'─'*32}╝\n")
#print(f"\n{'⚠': ^44}\n╔{'─'*42}╗\n|   Precisasse adicionar algum professor{'|': >4}\n╚{'─'*42}╝\n")
#print(f"\n{'⚠': ^44}\n╔{'─'*42}╗\n|     Precisasse adicionar algum aluno{'|': >6}\n╚{'─'*42}╝\n")
#print(f"\n╔{'─'*35}╗\n|      Turma criada com sucesso{'|': >6}\n╚{'─'*35}╝\n")
#print(f"\n╔{'─'*35}╗\n|     Turma editada com sucesso{'|': >6}\n╚{'─'*35}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n|     A turma não encontrada{'|': >6}\n╚{'─'*32}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|      Nome incorreto{'|': >6}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n|   A turma exclída com sucesso{'|': >3}\n╚{'─'*32}╝\n")


#   === NOVAS BASES ===
#  Bases que não quebram

#print(f"\n╔{'─'*40}╗\n|{f'{nome_dicionario.title()} deletado com sucesso!': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n╔{'─'*40}╗\n|{f'{nome_dicionario.title()} atualizado com sucesso!': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n╔{'─'*40}╗\n|{f'{nome_dicionario.title()} adicionado com sucesso!': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n╔{'─'*40}╗\n|{'Turma criada com sucesso': ^40}{'|': ^2}\n╚{'─'*40}╝\n")


#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Ação inválida':^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Ação interrompida':^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Matricula não encontrada': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{f'{nome_dicionario.title()} não encontrado': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{f'Nome inválido': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Nome deve conter apenas letras e': ^40}{'|': ^2}\n|{'deve ser composto': ^40}{'|': ^2}\n╚{'─'*40}╝")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Escolha inválida':^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Precisa ter alunos':^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Precisa ter professores':^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Precisa ter turmas':^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Precisa de ter pelo menos um':^40}{'|': ^2}\n|{'professor e um aluno cadastrados': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Precisa ter pelo menos uma':^40}{'|': ^2}\n|{'turma cadastrada': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{'Aluno não encontrado': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{f'Turma já existente': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{f'Turma não encontrada': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{f'Aluno já presente na turma': ^40}{'|': ^2}\n╚{'─'*40}╝\n")
#print(f"\n{'⚠': ^42}\n╔{'─'*40}╗\n|{f'Não encontrado': ^40}{'|': ^2}\n╚{'─'*40}╝\n")