#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|     Opção inválida!{'|': >6}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n| Nome não deve ser vazio{'|': >2}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|   Aluno não encontrado{'|': >3}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|    Ação interrompida{'|': >5}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^62}\n╔{'─'*60}╗\n|     Nome deve conter apenas letras e deve ser composto{'|': >6}\n╚{'─'*60}╝\n")
#print(f"\n{'⚠': ^32}\n╔{'─'*30}╗\n|   Matricula não encontrada{'|': >4}\n╚{'─'*30}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n| A matricula não pode ser vazia{'|': >2}\n╚{'─'*32}╝\n")
#print(f"\n╔{'─'*30}╗\n|  Aluno deletado com sucesso{'|': >3}\n╚{'─'*30}╝\n")
#print(f"\n╔{'─'*30}╗\n| Aluno adicionado com sucesso{'|': >2}\n╚{'─'*30}╝\n")
#print(f"\n╔{'─'*30}╗\n| Aluno atualizado com sucesso{'|': >2}\n╚{'─'*30}╝\n")
#print(f"\n{'⚠': ^30}\n╔{'─'*28}╗\n|  Professor não encontrado{'|': >3}\n╚{'─'*28}╝\n")
#print(f"\n╔{'─'*35}╗\n| Professor adicionado com sucesso{'|': >3}\n╚{'─'*35}╝\n")
#print(f"\n╔{'─'*35}╗\n| Professor atualizado com sucesso{'|': >3}\n╚{'─'*35}╝\n")
#print(f"\n╔{'─'*35}╗\n|   Professor deletado com sucesso{'|': >3}\n╚{'─'*35}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n|   A turma não pode ser vazia{'|': >4}\n╚{'─'*32}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|    Turma já existente{'|': >4}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n|   Aluno já presente na turma{'|': >4}\n╚{'─'*32}╝\n")
#print(f"\n{'⚠': ^44}\n╔{'─'*42}╗\n|   Precisasse adicionar algum professor{'|': >4}\n╚{'─'*42}╝\n")
#print(f"\n{'⚠': ^44}\n╔{'─'*42}╗\n|     Precisasse adicionar algum aluno{'|': >6}\n╚{'─'*42}╝\n")
#print(f"\n╔{'─'*35}╗\n|      Turma criada com sucesso{'|': >6}\n╚{'─'*35}╝\n")
#print(f"\n╔{'─'*35}╗\n|     Turma editada com sucesso{'|': >6}\n╚{'─'*35}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n|     A turma não encontrada{'|': >6}\n╚{'─'*32}╝\n")
#print(f"\n{'⚠': ^27}\n╔{'─'*25}╗\n|      Nome incorreto{'|': >6}\n╚{'─'*25}╝\n")
#print(f"\n{'⚠': ^34}\n╔{'─'*32}╗\n|   A turma exclída com sucesso{'|': >3}\n╚{'─'*32}╝\n")